@host = http://localhost:3001
@mid = 62fdad79931832efcfaa7bd7

### /chat custom test
GET {{host}}/chat/test HTTP/1.1

### create new message
POST {{host}}/chat/message/new HTTP/1.1
content-type: application/json

{
    "text": "Bye World!",
    "uid": "whoisthislolhehe"
}

### get message by message id
GET {{host}}/chat/message/{{mid}} HTTP/1.1
