@host = http://localhost:3001
@gameID = Ay513wY8St


### /game custom test
GET {{host}}/game/test HTTP/1.1

### create new game
POST {{host}}/game/new/ HTTP/1.1
content-type: application/json

{
    "uid": "qwertywarrior123456",
    "timeControl": "2+1"
}

### get game info with ID
GET {{host}}/game/{{gameID}}/ HTTP/1.1

### get random joinable game
GET {{host}}/game/random/open/ HTTP/1.1

### join game
POST {{host}}/game/{{gameID}}/join HTTP/1.1
content-type: application/json

{
    "uid": "poiuytrewq5311"
}

### leave game
POST {{host}}/game/{{gameID}}/leave HTTP/1.1
content-type: application/json

{
    "uid": "poiuytrewq5311"
}