@host = http://localhost:3001
@mid = 62fdad79931832efcfaa7bd7
@cid = 62fdd435a5678c11b62d8b5a

### /chat custom test
GET {{host}}/chat/test HTTP/1.1

### create new message
POST {{host}}/chat/message/new HTTP/1.1
content-type: application/json

{
    "text": "Bye World!",
    "username": "goodGuy12",
    "uid": "whoisthislolhehe"
}

### get message by message id
GET {{host}}/chat/message/{{mid}} HTTP/1.1

### create new chat room
POST {{host}}/chat/new HTTP/1.1

### get chat room
GET {{host}}/chat/{{cid}} HTTP/1.1

### post message to chat
POST {{host}}/chat/{{cid}}/new-message HTTP/1.1
content-type: application/json

{
    "text": "Bye World!",
    "username": "goodGuy12",
    "uid": "qoiwryuescvnb214"
}
