@host = http://localhost:3001
@gameID = 62fa6b6f68cf9dd078940cff

### get all games from database
GET {{host}}/ HTTP/1.1

### create new game
POST {{host}}/game/new/ HTTP/1.1
content-type: application/json

{
    "username": "asdf404"
}

### get game info with ID
GET {{host}}/game/{{gameID}}/ HTTP/1.1

### join game
POST {{host}}/game/{{gameID}}/join HTTP/1.1
content-type: application/json

{
    "username": "qwer"
}

### leave game
POST {{host}}/game/{{gameID}}/leave HTTP/1.1
content-type: application/json

{
    "username": "asdf404"
}
