@host = http://localhost:3001
@uid = qwertywarrior123456
@name = MaleMuskox50

### /user custom test
GET {{host}}/user/test HTTP/1.1

### create new user
POST {{host}}/user/new HTTP/1.1
content-type: application/json

{
    "uid": "houhouwoshouwa12"
}

### get user by uid
GET {{host}}/user/{{uid}} HTTP/1.1

### get user by name
GET {{host}}/user/name/{{name}} HTTP/1.1
