@host = http://localhost:3001
@gameID = 7pw8OlmTIT


### /game custom test
GET {{host}}/game/test HTTP/1.1

### create new game
POST {{host}}/game/new/ HTTP/1.1
content-type: application/json

{
    "uid": "qwertywarrior123456",
    "timeControl": "10+9"
}

### get game info with ID
GET {{host}}/game/{{gameID}}/ HTTP/1.1

### get random joinable game
GET {{host}}/game/random/open/ HTTP/1.1

### join game
POST {{host}}/game/{{gameID}}/join HTTP/1.1
content-type: application/json

{
    "uid": "houhouwoshouwa12"
}

### leave game
POST {{host}}/game/{{gameID}}/leave HTTP/1.1
content-type: application/json

{
    "uid": "houhouwoshouwa12"
}

### user1 clicked on ready button
POST {{host}}/game/{{gameID}}/ready HTTP/1.1
content-type: application/json

{
    "uid": "houhouwoshouwa12"
}

### start game
POST {{host}}/game/{{gameID}}/start HTTP/1.1
content-type: application/json

{
    "uid": "qwertywarrior123456"
}
